name: geist-linux-docker
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h68df207_7
  - ca-certificates=2024.12.14=hcefe29a_0
  - click=8.1.8=pyh707e725_0
  - h11=0.14.0=pyhd8ed1ab_1
  - ld_impl_linux-aarch64=2.43=h80caac9_2
  - libblas=3.9.0=26_linuxaarch64_openblas
  - libcblas=3.9.0=26_linuxaarch64_openblas
  - libexpat=2.6.4=h5ad3122_0
  - libffi=3.4.2=h3557bc0_5
  - libgcc=14.2.0=he277a41_1
  - libgcc-ng=14.2.0=he9431aa_1
  - libgfortran=14.2.0=he9431aa_1
  - libgfortran5=14.2.0=hb6113d0_1
  - libgomp=14.2.0=he277a41_1
  - liblapack=3.9.0=26_linuxaarch64_openblas
  - liblapacke=3.9.0=26_linuxaarch64_openblas
  - liblzma=5.6.3=h86ecc28_1
  - libnsl=2.0.1=h31becfc_0
  - libopenblas=0.3.28=pthreads_h9d3fd7e_1
  - libsqlite=3.48.0=h5eb1b54_0
  - libstdcxx=14.2.0=h3f4de04_1
  - libuuid=2.38.1=hb4cce97_0
  - libxcrypt=4.4.36=h31becfc_1
  - libzlib=1.3.1=h86ecc28_2
  - mlx=0.22.0=py311h8a546bd_0
  - ncurses=6.5=ha32ae93_2
  - openssl=3.4.0=hd08dc88_1
  - pip=24.3.1=pyh8b19718_2
  - python=3.11.11=h1683364_1_cpython
  - python_abi=3.11=5_cp311
  - readline=8.2=h8fc344f_1
  - setuptools=75.8.0=pyhff2d567_0
  - tk=8.6.13=h194ca79_0
  - typing_extensions=4.12.2=pyha770c72_1
  - uvicorn=0.20.0=py311hfecb2dc_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiohttp-retry==2.9.1
      - aiosignal==1.3.2
      - alembic==1.15.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - attrs==25.1.0
      - blobfile==3.0.0
      - certifi==2024.12.14
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - datasets==3.5.0
      - dill==0.3.8
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - fastapi==0.115.6
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - greenlet==3.1.1
      - hf-transfer==0.1.9
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - idna==3.10
      - iniconfig==2.0.0
      - jinja2==3.1.5
      - kagglehub==0.3.10
      - lxml==5.3.1
      - mako==1.3.10
      - markupsafe==3.0.2
      - mimetypes-magic==0.4.30
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.2
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - pluggy==1.5.0
      - propcache==0.2.1
      - psutil==6.1.1
      - psycopg2-binary==2.9.10
      - pyarrow==19.0.1
      - pycryptodomex==3.22.0
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pyjwt==2.10.1
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.2
      - sentencepiece==0.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.37
      - starlette==0.41.3
      - sympy==1.13.1
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - torch==2.5.1
      - torchao==0.10.0
      - torchaudio==2.5.1
      - torchdata==0.11.0
      - torchtune==0.6.0
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.48.1
      - twilio==9.4.4
      - tzdata==2025.2
      - urllib3==2.3.0
      - websockets==15.0.1
      - xxhash==3.5.0
      - yarl==1.18.3
      - langchain==0.3.13
      - langchain-core==0.3.28
      - langgraph==0.2.62
      - langgraph-checkpoint==2.0.6
prefix: /root/miniconda3/envs/geist-linux-docker
