name: geist-mac
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.12.31=hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.15=h80987f9_0
  - pip=25.0=py310hca03da5_0
  - python=3.10.16=hb885b13_1
  - readline=8.2=h1a28f6b_0
  - setuptools=75.8.0=py310hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiohttp-retry==2.9.1
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - blobfile==3.0.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - datasets==3.5.0
      - dill==0.3.8
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - fastapi==0.115.8
      - filelock==3.17.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - h11==0.16.0
      - hf-transfer==0.1.9
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - idna==3.10
      - iniconfig==2.1.0
      - jinja2==3.1.5
      - kagglehub==0.3.11
      - lxml==5.3.1
      - markupsafe==3.0.2
      - mimetypes-magic==0.4.30
      - mlx==0.23.1
      - moshi==0.2.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy==1.13.0
      - networkx==3.4.2
      - numpy==2.2.3
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pillow==11.1.0
      - pluggy==1.5.0
      - pre-commit==4.0.1
      - propcache==0.2.1
      - psycopg2==2.9.10
      - pyarrow==19.0.1
      - pycparser==2.22
      - pycryptodomex==3.22.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyjwt==2.10.1
      - pytest==8.3.5
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - ruff==0.8.4
      - safetensors==0.5.2
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - sounddevice==0.5.0
      - sphn==0.1.12
      - sqlalchemy==2.0.38
      - starlette==0.45.3
      - sympy==1.13.1
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.6.0
      - torchao==0.9.0
      - torchaudio==2.6.0
      - torchdata==0.11.0
      - torchtune==0.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.48.3
      - twilio==9.4.5
      - types-PyYAML==6.0.12.20240917
      - types-python-dateutil==2.9.0.20241206
      - types-requests==2.32.0.20241016
      - types-six==1.16.21.20240513
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - websockets==15.0.1
      - xxhash==3.5.0
      - yarl==1.18.3
prefix: /Users/daviddworetzky/miniconda3/envs/geist-mac
